### ISSUE TITLE
archived user able to login to system, add archive checks on getItem method in interpreter

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#183]
1. archived user able to login to system, add archive checks on getItem method in interpreter
2. should not able to login

**Comment by kartikatyagi** [comment]
Expected behavior:  Archive user should not be able to login 

Actual behavior : The system is working as expected archive user is not able to login 
Tested and passed

Screenshots attached: 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/08815818-3c53-4c1c-9402-6c312c00f018)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/99def75b-e5ec-4fe0-8947-6e5a33f294ff)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/e695b4ad-13df-4f01-b39a-b0f6838a1184)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/d407ec5d-b90e-4d42-ae83-3527828fc875)

**After enabling the archived user it  is able to login**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/aeea41e6-4806-4ced-80d6-eb9f05db7b1b)

**Comment by Adnan-shariff** [comment]
working as intended .
![2024-06-27 11_35_36-Settings](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b3dd8ca4-7679-4115-af9b-e51e33988cad)
