### ISSUE TITLE
invalid token issue

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#186]
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/8902b70a-2d9d-4d18-9273-79be4bf13bca)

**Comment by kartikatyagi** [comment]
Describe the bug
invalid token issue

Steps to reproduce the behavior:

1.Navigate to the login page of the web application.
 2.Enter valid username.
 3.Enter valid password.
 4.Click on the "Login" button.

Expected behavior
1.User should be logged in successfully.
 2.Verify that the user is redirected to the home/dashboard page.
 3.Verify that user-specific content or options are visible.

Actual behavior:
User is able to login successfully with valid email and password

Screenshots attached :
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/0c724e16-0d5a-4299-8c34-f87549102717)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/69bdc22e-be8e-4516-a4b5-4e314dd1a477)
