### ISSUE TITLE
Type of evaluation:  Ug Complete Transcript Available question: Error message not user friendly

### ISSUE THREAD

**Issue by Adnan-shariff** [Globalshala/Eval-Bridge-bugs#201]
**Describe the bug**
Error message contains technical name which might not be understandable to End user

**Steps to reproduce**
1.Start a New app
2.Dont fill any data click on Next
3.Error messages are displayed 

**Expected Behavior**
It’s better to rephrase the message into something more understandable and relevant to the user's context

**Actual Behavior**
Error message displays "ug_is_transcript_complete is a required field"

**Screenshots**
![2024-06-26 17_37_14-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/34e26607-5d05-4521-a5fc-1e5c2f9042c8)

**Comment by kartikatyagi** [comment]
Describe the bug
Error message contains technical name which might not be understandable to End user

Expected Behavior
It’s better to rephrase the message into something more understandable and relevant to the user's context

Actual Behavior
It is working as expected Error message displays "UG transcript Complete field is required."

![image](https://github.com/user-attachments/assets/59b65e49-faf3-4912-96e0-cc5f0d374201)
