### ISSUE TITLE
Create user issue

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#21]
**Describe the bug**
when we create an user at that time we are uploading profile pic. and after successfully creation of user profile pic is still there.
**To Reproduce**
1. Go to 'create user'
2. Fill all details
3. submit the details

**Expected behavior**
profile pic should be removed

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/389e075f-4aeb-4526-92e5-5eedf1a087b6)`

**Comment by kartikatyagi** [comment]
Describe the bug
when we create an user at that time we are uploading profile pic. and after successfully creation of user profile pic is still there.
To Reproduce
Steps to reproduce the behavior:

Go to 'create user'
upload profile pic
Fill all details
submit the details

Expected behavior
profile pic should be removed

Actual Behavior
The system works as expected when we create an user at that time we are uploading profile pic. and after successfully creation of user profile pic should be removed
Screenshot attached 
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/122828e6-baa4-45fb-9d5a-16e3fb1f4660)

**Comment by Adnan-shariff** [comment]
working as intended.
