### ISSUE TITLE
Credits column in Ug Course by Course page doesn't accept value between 0 to 1

### ISSUE THREAD

**Issue by RajdeepGlobalshala** [Globalshala/Eval-Bridge-bugs#32]
The credits column in Ug Course by Course page doesn't accept value between 0 to 1 (eg, 0.73, 0.5, 0.67 etc)

![Screenshot_2024-03-06-16-33-38-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/73563eec-049f-4865-8cb1-b0e522bf87f5)
![Screenshot_2024-03-06-16-24-20-42_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/ef8db857-6667-48c7-b9bd-cf8c6707beee)
![Screenshot_2024-03-06-16-30-12-80](https://github.com/Globalshala/Eval-Bridge-bugs/assets/157602910/51f8b0b4-82fb-4dcd-9b31-6b9bd735b000)

**Comment by Adnan-shariff** [comment]
**Describe the bug**
The credits column in the UG Course by Course page does not accept values between 0 to 1.

**Scope of the bug**
UG Course by Course Page
PG Course by course Page

**Steps to Reproduce**
Navigate to the UG/PG Course by Course page.
Try to input a value between 0 to 1 in the credits column.

**Expected Behavior**
The credits column should accept values between 0 to 1.

**Actual Behavior**
The credits column does accept values between 0 to 1. 

**Screenshots**
![0 1 3 4](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/970b0e8d-8e7c-40a3-a055-e8c60eead30a)
![0 1 5](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c3bfcd7f-72b0-478e-a0d7-7f6e0d8f2f8d)
![0-1 3](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/d81bda54-5491-4797-8510-f1e172e6a05a)
![0-1 dpu64](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/eec88b28-e255-4299-a368-929c352f9874)
![0-1cua](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/18bfd2a6-5cc1-447f-b23b-022e50accd11)
![0-1cua2](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/23e5983b-8519-44df-baac-8aa55f59b37a)
![0-1cua3](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/79fca2a3-f935-485d-9587-c01da215a197)
![0-1-cua8](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c7712ffd-8311-43a6-b446-2c8cd964d13e)
![0-1dpu](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c56a9b7d-c051-45a6-99ef-5fba998affb3)

**Comment by shivanim11** [comment]
Fixed in dev
