### ISSUE TITLE
Grade Scales  UI issue

### ISSUE THREAD

**Issue by karodisuresh** [Globalshala/Eval-Bridge-bugs#40]
1. In the search function and remove button there is no gap between we need to modify the UI with some gap instead both 

![Screenshot 2024-03-13 193000](https://github.com/Globalshala/Eval-Bridge-bugs/assets/103185383/82e10d62-c6e2-4c37-a0c9-af53ab40d978)
2. For the AND || ON Buttons We need create a Drop down functionality

**Comment by NavnathGunjal7** [comment]
it will be done in next iterations I have added as enhancement please test funcitonality

**Comment by NavnathGunjal7** [comment]
@Harsh-GlobalShala  please come up with UI improvisation how we can improvise UI we can discuss with @mansi38299  and implement it

**Comment by kartikatyagi** [comment]
Describe the bug
1.In the search function and remove button there is no gap between we need to modify the UI with some gap instead both
2. For the AND || ON Buttons We need create a Drop down functionality

Steps to reproduce the behavior:

Go to 'Grade Scales'
Click on 'search grade scales'
click on "AND" || "OR"
then click on AND country dropdown and 
Equal to dropdown 
then click on OR country dropdown and 
Equal to dropdown 

Expected behavior
1.In the search function and remove button there is no gap between 
2.There should  be dropdown functionality for AND|| OR

Actual behavior:
1.The system works as expected  In the search function and remove button there is no gap between 
2.The system works as expected dropdown functionality for AND|| OR is working 

Screenshots attached :

**Comment by kartikatyagi** [comment]
Describe the bug
1.In the search function and remove button there is no gap between we need to modify the UI with some gap instead both
2. For the AND || ON Buttons We need create a Drop down functionality

Steps to reproduce the behavior:

Go to 'Grade Scales'
Click on 'search grade scales'
click on "AND" || "OR"
then click on AND country dropdown and 
Equal to dropdown 
then click on OR country dropdown and 
Equal to dropdown 

Expected behavior
1.In the search function and remove button there is no gap between 
2.There should  be dropdown functionality for AND|| OR

Actual behavior:
1.The system works as expected  In the search function and remove button there is no gap between 
2.The system works as expected dropdown functionality for AND|| OR button  is working 

Screenshots attached : 
Gap b/w search and remove button
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/869dfd5e-03f8-4477-aa58-97f659131478)

dropdown functionality for AND|| OR button :
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/9365f9e2-5923-48ae-96cb-761d019ab65b)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/4453c444-e770-469c-ad96-0b7161414bfa)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/919cc9a7-b363-4206-8097-c088d0f0157b)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/bc308dfa-1dec-4c76-be4f-3cfbf7f82ea4)
