### ISSUE TITLE
clear all data for cbc 

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#47]
1, create a button that will be clearing all cbc data filled

**Comment by Adnan-shariff** [comment]
**Describe the bug**
a button should be present to clear CBC data after filling the details 

**Expected Behavior**
After filling CBC data, there should be a button available to clear the filled CBC data.

**Actual Behavior**
The button is present to clear CBC data after filling 

**Screenshots**

![51qa](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/c084e43a-68ff-48a0-9218-3e827eab64ec)
![51qa2](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/8977ad9b-8249-4acd-b8a7-1f73f5cbb8a3)
