### ISSUE TITLE
issue in cua templates

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#48]
1. issue in cua templates alignments
Output Changes for CUA AE: - 
Academic Evaluation Report Should be left aligned.
We do not require Letter grade and bracket in US GPA.
The spacing after General Information and Evaluation Summary should be same.
Column Width for Evaluation Summary Headings should be reduced to left. 
US GPA and US Credit column width should be equal in Course by Course Evaluation.

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff please test and close

**Comment by kartikatyagi** [comment]
Describe the bug
issue in cua templates alignments
Output Changes for CUA AE: -
Academic Evaluation Report Should be left aligned.
We do not require Letter grade and bracket in US GPA.
The spacing after General Information and Evaluation Summary should be same.
Column Width for Evaluation Summary Headings should be reduced to left.
US GPA and US Credit column width should be equal in Course by Course Evaluation.

Steps to reproduce the behavior:

Enter all the required evaluation details for  undergraduate 
Click on the "Save" button to save the details
click on 'course by course'  fill all the required details 
then click on "save" button
Go to UG evaluation and click on "UG evaluation" button 
Click on "Preview"
Check the Academic Evaluation report.

Expected behavior
Academic Evaluation Report Should be left aligned.
We do not require Letter grade and bracket in US GPA.
The spacing after General Information and Evaluation Summary should be same.
Column Width for Evaluation Summary Headings should be reduced to left.
US GPA and US Credit column width should be equal in Course by Course Evaluation
 

Actual behavior:
The system works as expected Academic Evaluation Report is left aligned.
There is no  Letter grade and bracket in US GPA.
Column Width for Evaluation Summary Headings is reduced to left.
US GPA and US Credit column width is equal in Course by Course Evaluation.
**The system in not working as expected for this scenario as The spacing after General Information and Evaluation Summary is not same.**


Screenshots attached :

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/1effcea8-474f-49aa-b332-9171f367e6ca)

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/dab24eaf-8b6e-48ec-9442-78d82b7e6d8c)

**Comment by kartikatyagi** [comment]
This this is not fixed check once for this : **The system in not working as expected for this scenario as The spacing after General Information and Evaluation Summary is not same.**

**Comment by Adnan-shariff** [comment]
@NavnathGunjal7 please check if it is working as expected let me know i will close

**Comment by NavnathGunjal7** [comment]
As this is on prod and no comments from eval team so marking as fixed
