### ISSUE TITLE
Filter the applications when we assign it to user

### ISSUE THREAD

**Issue by shivanim11** [Globalshala/Eval-Bridge-bugs#5]
**Describe the bug**
we should filter the applications when we are assigning that to user. if that application is already in someonce plate and we are tying to assign it to other user then it is throwing error.
**To Reproduce**

**Expected behavior**
when we select the university then applications which we are getting those should be filtered. i.e. not assigned

**Screenshots**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/130555898/245f2419-20eb-400d-b727-759f04a18cd0)

**Comment by NavnathGunjal7** [comment]
@Harsh-GlobalShala  Additional changes:
1. as we are querying all aplications there api will be heavy and it will take time to respond when applications increase
2. Solution : add begins with query for searching in backend and improvise api for search instead of querying all application search when application number is typed add debouncing logic  so we can avoid multiple api calls on search

**Comment by mansi38299** [comment]
@MSGlobalShala @Harsh-GlobalShala @NavnathGunjal7 

Expected behaviour: When We will select the organisation, We will get list of all the Application which is Assignable for review or evaluate
that means Any Application whose status value in App table is not equal to 5 , is a part of that list.

Search debouncing will be creating confusion to user, as for the very first time the dropdown , No application found.

**Comment by NavnathGunjal7** [comment]
> @MSGlobalShala @Harsh-GlobalShala @NavnathGunjal7 
> 
> Expected behaviour: When We will select the organisation, We will get list of all the Application which is Assignable for review or evaluate
> that means Any Application whose status value in App table is not equal to 5 , is a part of that list.
> 
> Search debouncing will be creating confusion to user, as for the very first time the dropdown , No application found.

@mansi38299 we can add placeholder to add aplication I'd I have Told to add search deboucing with appid because when we are having too many applications api will be slow as it has to qury whole app table with search deboucing we will be doing begins with

**Comment by mansi38299** [comment]
@NavnathGunjal7 
What if we show first 10-20 records, rest will come under search or scrolling down ?

**Comment by mansi38299** [comment]
Also, in the dropdown, We should show Appid ( Eval_inprogress)
I mean AppId( status value )to give clear visibility

**Comment by kartikatyagi** [comment]
working as expected 
Now the applications are filtered with respect to their status
![image](https://github.com/user-attachments/assets/58f02c1f-c58e-46c4-baf8-95ec48222a5f)
 
The application whose status is review complete are not showing under the dropdown 
![Uploading image.png…]()

Infinite scroll is working under the select appid dropdown along with the api calls 
![image](https://github.com/user-attachments/assets/5d343a36-82cf-4869-9293-74d1dae15a6d)
