### ISSUE TITLE
Loader should be disable after clicking on  Fetch Prev Data

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#51]
When clicked on fetch prev data, the loader is there on the Fetch Prev Data button and the clear cbc data button is also disabled

![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/b9546549-a64d-4b76-8402-cbe615fb89b5)

**Comment by Adnan-shariff** [comment]
**Describe the bug**
Currently, the loader does not disable after clicking on the "Fetch Prev Data" button.

**Scope of the bug**
CBC Page: Fetch Previous Data

**Expected Behavior**
The loader should disable after clicking on the "Fetch Prev Data" button .

**Actual Behavior**
The loader is disabled after clicking on the "Fetch Prev Data" button.
Clear CBC data button remains disabled because no data is filled in CBC data

![prevfetchdataloader](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a6cc1a35-f90c-480c-8be6-c2c269785fdc)
![prevfetchdataloader2](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/b548e703-94bb-4567-8df8-d79d62545f05)

**Comment by shivanim11** [comment]
Fixed
