### ISSUE TITLE
Runtime error when  major or University name is changed before fetching prev data in cbc page

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#53]
Steps - 
1. Saved one application cbc data to fetch in another application
2. In other application put the university or major name wrong
3. click on Fetch prev data in cbc page
4. error

![MicrosoftTeams-image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/144761726/23effd2e-0b5a-4f87-81a0-88054299f09f)

**Comment by Adnan-shariff** [comment]
**Describe the bug**
When trying to fetch previous data on the CBC page after changing the university or major name to an incorrect value, a runtime error occurs.

**Scope of the bug**
CBC > Fetch Previous Data

**Steps to Reproduce**
Save an application with CBC data to fetch in another application.
Appid: slu112276 -
University- VTU
Major-MBA

In the other application, enter an incorrect university or major name.
Univeristy: Mumbai
Major: Accounts
Click on "Fetch Previous Data" on the CBC page.

**Expected Behavior**
The system should handle incorrect university or major names,and not cause a runtime error when fetching previous data.

**Actual Behavior**
The system works as expected and does not cause any runtime error despite entering an incorrect university or major name before fetching previous data.

**Screenshots**
![noruntimeerror1](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/32846056-d16f-4c7c-9327-665cae89791c)
![noruntimeerror2](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/edeb5997-bbb9-4aa6-8b87-76542f0b7f04)
![noruntimeerror3](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/cfbbf942-1528-442a-8759-74ad41d95733)
![runtimeerror4](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/9cb74df7-6883-4c01-ac86-3429181538c9)
![runtimeerror6](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/625a08a9-6ace-4846-98c6-ddcafcb6ef57)

**Comment by NavnathGunjal7** [comment]
@AnkitExcelerate  please test and close

**Comment by kartikatyagi** [comment]
Describe the bug
When trying to fetch previous data on the CBC page after changing the university or major name to an incorrect value, a runtime error occurs.

Scope of the bug
CBC > Fetch Previous Data

Steps to Reproduce
Save an application with CBC data to fetch in another application.
Appid: slu43211234 -
University-  Acharya Nagarjuna university
Major-EC

In the other application, enter an incorrect university or major name.
Appid: cua66977
Univeristy: University of Ghana
Major: M.Tech
Click on "Fetch Previous Data" on the CBC page.

Expected Behavior
The system should handle incorrect university or major names,and not cause a runtime error when fetching previous data.

Actual Behavior
The system works as expected and does not cause any runtime error despite entering an incorrect university or major name before fetching previous data.

Screenshots
**UG Course by Course**
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/f9a398fe-78dc-4aee-a85c-736718cda580)

UG Course by Course
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/6987b09a-0e6b-4571-af53-e27501f1b3f7)

**Comment by Adnan-shariff** [comment]
working as intended. 
please check the screenshots attached . 
![2024-06-25 18_10_11-](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a1f5e955-5f0a-4b9b-8353-bc02bb31fb8b)
