### ISSUE TITLE
 send back to evaluator in high school, correct names in preview and report for high school

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#75]
**Describe the bug**
 send back to evaluator in high school, correct names in preview and report for high school

**To Reproduce**
1. there is no send back to evaluator option in high schools

**Expected behavior**
1. there should be send back to evaluator button

**Screenshots**
1. so for highschool instead of undergrad it should be high school 1
![MicrosoftTeams-image (8)](https://github.com/Globalshala/Eval-Bridge-bugs/assets/108262338/18e144d3-d68b-498d-9c2b-152b04c2d694)

**Comment by Adnan-shariff** [comment]
not fixed in dev please check the screenshots attached. 
![75 hs names have not been fixed ](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/a66c9824-11a0-4bd2-9d9e-2eafa5aaeb13)
![75 send back to evaluator button is not fixed](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e86459cf-161a-452b-b8ef-517dcabf520b)

**Comment by Adnan-shariff** [comment]
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/e7152392-0a4d-401c-92f8-7ecfd47773df)

**Comment by shivanim11** [comment]
Fixed
