### ISSUE TITLE
depaul reports testing

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#80]
1. check the generated reports and preview in dev should match with following reports 
2. also confirm comprehensive gpa generated by filling this data
3. Increase width of Course Column in Preview and decrease the width of US Credits
4.  Bachelor GPA is coming Fine

[Nora Hayford_641569516 (1).pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/15094060/Nora.Hayford_641569516.1.pdf)
[Chandra Mouli Medicherla_074961365 (1).pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/15094064/Chandra.Mouli.Medicherla_074961365.1.pdf)
[Mukesh Raja P_102118545.pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/15094066/Mukesh.Raja.P_102118545.pdf)
[Abdul.Abrarr.Mohammed_425171018 (1).pdf](https://github.com/Globalshala/Eval-Bridge-bugs/files/15094068/Abdul.Abrarr.Mohammed_425171018.1.pdf)

**Comment by NavnathGunjal7** [comment]
@Adnan-shariff  , @AnkitExcelerate  test and close please add comments both of you when comments added close it

**Comment by kartikatyagi** [comment]
DPU > Evaluation > Evaluation Report>DyamoDB

Steps to Reproduce:
Evaluation
Degree of Evaluation:
Undergraduate (UG) and Postgraduate (PG)
Type of Evaluation: Course-by-Course (CBC)

For instance
Select all subjects as PASS for bith UG and PG Test case 1,
Choose the score or scale indicating that all subjects have been successfully passed.
Select 2 subjects as failed for both UG and PG IN  Test case 2,
Indicate the selection of a score or scale that designates failure for two subjects.

FIll all the details
Click on Preview to Verify the Evaluation report

Expected Behavior:
Failed marks should be highlighted in red within the tabular column of the evaluation report.

Actual Behavior:
The System is functioning as intended.

Please check the screenshots attached.

**Comment by kartikatyagi** [comment]
Scope of the Bug:
DPU > Evaluation > Evaluation Report>DyamoDB

Steps to Reproduce:
Evaluation
Degree of Evaluation:
Undergraduate (UG) and Postgraduate (PG)
Type of Evaluation: Course-by-Course (CBC)

For instance
Select all subjects as PASS for bith UG and PG Test case 1,
Choose the score or scale indicating that all subjects have been successfully passed.
Select 2 subjects as failed for both UG and PG IN  Test case 2,
Indicate the selection of a score or scale that designates failure for two subjects.

FIll all the details
Click on Preview to Verify the Evaluation report

Expected Behavior:
Failed marks should be highlighted in red within the tabular column of the evaluation report.

Actual Behavior:
The System is functioning as intended.

Please check the screenshots attached.   
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/f1db53cd-dbf2-4b65-8c75-41bb6bbbc98f)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/1261df33-5fda-425a-be0a-cef6612e562b)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/5e417710-e207-40ef-8ef2-c42fc5801af0)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/fbf42fe9-84f0-4ed1-aab7-e2fd7a42ea43)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/cd4b82fa-a967-43d8-a823-06ffc0847e11)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/d13d154b-42ce-4875-b506-8fae3d67ca42)

**Comment by kartikatyagi** [comment]
Scope of the Bug:
DPU > Evaluation > Evaluation Report

Steps to Reproduce:
Evaluation
Degree of Evaluation:
Undergraduate (UG) and Postgraduate (PG)
Type of Evaluation: Course-by-Course (CBC)

For instance
Select all subjects as PASS for both UG and PG Test case 1,
Choose the score or scale indicating that all subjects have been successfully passed.
Select 2 subjects as failed for both UG and PG IN  Test case 2,
Indicate the selection of a score or scale that designates failure for two subjects.

Fill all the details
Click on Preview to Verify the Evaluation report

Expected Behavior:
Failed marks should be highlighted in red within the tabular column of the evaluation report.

Actual Behavior:
The System is functioning as intended.

Please check the screenshots attached.   
PASS for both UG and PG Test case 1:
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/f1db53cd-dbf2-4b65-8c75-41bb6bbbc98f)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/1261df33-5fda-425a-be0a-cef6612e562b)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/5e417710-e207-40ef-8ef2-c42fc5801af0)
failed for both UG and PG in Test case 2:
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/fbf42fe9-84f0-4ed1-aab7-e2fd7a42ea43)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/925c0c38-c31d-48c8-a091-2fc72690b720)
![image](https://github.com/Globalshala/Eval-Bridge-bugs/assets/173346103/d13d154b-42ce-4875-b506-8fae3d67ca42)
